### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by miqbal23** [ryanwongsa/Real-time-multi-style-transfer#1]
Hello, I'm browsing your repo and interested in using it. In your example, you used COCO dataset

Is it possible to use custom dataset on your code. If so, how do I organize the dataset (and style)?

**Comment by ryanwongsa** [comment]
Hi,

Yeah, the instructions on how you specify the folders containing the images for the different styles and training images is [here](https://github.com/ryanwongsa/Real-time-multi-style-transfer#usage).

Currently it only supports jpg but you can change the extension for the training images in the dataloader [here](https://github.com/ryanwongsa/Real-time-multi-style-transfer/blob/master/dataloaders/PhotoDataset.py#L15) and style [here](https://github.com/ryanwongsa/Real-time-multi-style-transfer/blob/master/trainstylenet.py#L48)
